name: Rodar microserviço backend

on: [push, pull_request]

jobs:
  run-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # isso garante que tudo roda dentro da pasta /backend

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências do backend
      run: npm install

    - name: Criar o .env com DATABASE_URL
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

    - name: Rodar o servidor por 10 segundos (teste de conexão)
      run: |
        node index.js &
        sleep 10
